# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 216311151819b68f77e9843c230f8cccf83121f955abac764a7c72f527361a692b4fd0555574aef9288b1d31f97d4a8d2d532a3deedcd647a2f7766ec373ee8e

test:
  secret_key_base: b5194e6c8138740347f03111f105603275eba1600f4ea71e5612fc9669f1b619c5b12e7fa5df4dc38525f452bb03193db950e1852ac3fe3e1bddeff0e77b6a67

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
